resolver: lts-11.3
#resolver: lts-8.24

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
# - location:
#    git: https://github.com/commercialhaskell/stack.git
#    commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#   extra-dep: true
#  subdirs:
#  - auto-update
#  - wai
#
# A package marked 'extra-dep: true' will only be built if demanded by a
# non-dependency (i.e. a user package), and its test suites and benchmarks
# will not be run. This is useful for tweaking upstream packages.
packages:
- .
  #- /home/portnov/src/distributed-process-client-server
  #- /home/portnov/src/progs/haskell/iso8583-bitmaps
  #- /home/portnov/src/progs/haskell/heavy-logger/heavy-logger-instances

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
  - iso8583-bitmaps-0.1.1.0
  - heavy-logger-0.3.2.0
  - heavy-logger-instances-0.2.0.0
  - text-format-heavy-0.1.5.1
  - distributed-process-0.7.3
  - distributed-process-p2p-0.1.4.0
    #- distributed-process-client-server-0.2.3

    #- distributed-process-p2p-0.1.3.2
    #  - lifted-base-0.2.3.12

